# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tatooklit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_806bfcb8fbb5487eaf6ac4115c81e86c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7169a7f6969f42138c4ad0b61bdca70f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_806bfcb8fbb5487eaf6ac4115c81e86c }}/tatoolkit:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tatooklit'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4b295e7cf6be47a5b6c56d79322a6507 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_806bfcb8fbb5487eaf6ac4115c81e86c }}/tatoolkit:${{ github.sha }}'
